name: engelsburg_app
description: Eine App von Dario Trombello, die Informationen über das Engelsburg-Gymnasium übersichtlich zusammenstellt.
version: 1.3.1+6

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info: ^0.4.1
  flutter_html: ^0.11.1
  flutter_map: ^0.8.2
  flutter_wordpress: ^0.1.4
  html: ^0.14.0
  html_unescape: ^1.0.1
  native_pdf_view: ^2.1.1
  package_info: ^0.4.0
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  weather_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Medium.ttf

  assets:
   - assets/applogo.png
   - assets/logoengelsburg.png
   - assets/school.jpg
   - assets/schuelerzeitung.pdf
   - assets/weather-background.jpg
