name: engelsburg_app
description: Eine App von Dario Trombello, die Informationen über das Engelsburg-Gymnasium übersichtlich zusammenstellt.
version: 1.4.1+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.4.2
  flutter_html: ^1.0.2
  google_maps_flutter: ^0.5.30
  html: ^0.14.0
  html_unescape: ^1.0.1
  http: ^0.12.2
  intl: ^0.16.1
  native_pdf_view: ^3.8.0
  package_info: '>=0.4.3 <2.0.0'
  shared_preferences: '>=0.5.10 <2.0.0'
  url_launcher: ^5.5.0
  weather_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/documents/schuelerzeitung.pdf
   - assets/images/applogo.png
   - assets/images/logoengelsburg.png
   - assets/images/school.jpg
   - assets/images/weather-background.jpg

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Black.ttf
          weight: 900
